# Dependencies
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - [jekyll-paginate]

# Site settings
title: Dispatches from the Vale
tagline: 'observations on systems, markets, and complexity'
description: 'observations on systems, markets, and complexity'
url: "https://valeobserver.xyz"
baseurl: ""
imageurl: /assets/images

#Author
author:
  name: Lucian Vale
  email: 

social: 
  twitter: 
  instagram: 
  tiktok: 

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock



# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
